### ISSUE TITLE
Invalid palette map in pdf_images.py

### ISSUE THREAD

**Issue by cjemmott** [ronanpaixao/PyPDFTK#9]
Thanks for the improvements on image extraction code that is floating around!

I am having some trouble with indexed color spaces for the Flate Decode filter.  Specifically, the line:
`
    img.putpalette(lookup.getData())
`

It fails for color maps that are longer than 768 entries with the error:
`
    ValueError: invalid palette size
`

For images with a color index that is shorter, it seems like the image isn't being rendered correctly - I see really strange results.

I have attached a pdf with examples of images that have color index length from 368 to 956, so you can see both failure modes.  The code does seem to work when the color index is exactly 768.

[0198008e-8628-47be-b674-a4e26a419e98.pdf](https://github.com/ronanpaixao/PyPDFTK/files/1988432/0198008e-8628-47be-b674-a4e26a419e98.pdf)

**Comment by ronanpaixao** [comment]
Sorry. Didn't see your report until yesterday. It shall be fixed now.

The problem was that the images in your file were Indexed, but on a CMYK palette, and PIL's palette support is very weak. What I did to work around this weakness was to manually translate the palette values into a CMYK image. I also made a number of fixes related to CMYK images.

Thanks for the file! It should be extracting fine now with [v1.1.2](https://github.com/ronanpaixao/PyPDFTK/releases/tag/v1.1.2).
